### ISSUE TITLE
Giving out `&mut Node`s is unsound

### ISSUE THREAD

**Issue by michiel-de-muynck** [oooutlk/trees#1]
When functions like `root_mut()` and `first_mut()` give out `&mut Node`s, the user can move these nodes around through safe functions like the standard library's `std::mem::swap` and `std::mem::replace`. This invalidates the pointers that are part of these `Node`s, and they may start pointing to `Node`s belonging to different trees, or even to `Node`s that have been deallocated.

# Example

```rust
use trees::linked::singly::tr;

#[derive(Debug)]
struct LoudDrop {
	name: &'static str
}

impl LoudDrop {
	fn new(name: &'static str) -> LoudDrop {
		LoudDrop {
			name
		}
	}
}

impl Drop for LoudDrop {
	fn drop(&mut self) {
		println!("Dropping {}", self.name);
	}
}

fn main() {
	let mut tree1 = tr(LoudDrop::new("a")) /tr(LoudDrop::new("b"));
	let mut tree2 = tr(LoudDrop::new("c")) /tr(LoudDrop::new("d"));
	
	std::mem::swap(tree1.root_mut().last_mut().unwrap(), tree2.root_mut().last_mut().unwrap());
	
	drop(tree1);
	// this prints
	// "dropping b"
	// "dropping d"
	// "dropping a"
	
	// but then
	println!("tree2's child's name: {:?}", tree2.root().last().unwrap().data.name);
	// prints tree2's child's name: "b"? But we dropped b already!

	// when dropping tree2 at the end of this scope, the program crashes.
}
```

**Comment by oooutlk** [comment]
Really appreciate that you created the first issue for my project. I fixed it using `Pin<&mut _>`, and bumped the version to 0.3.0. Now rustc will stop you from doing so, with a compiler error.
