### ISSUE TITLE
[Feature request] Implement From<String> for Tree

### ISSUE THREAD

**Issue by OhBonsai** [oooutlk/trees#5]
```

impl From<String> for Tree {
    fn from(item: String) -> Self {
        unimplement!
    }
}

```

**Comment by OhBonsai** [comment]
Hello, @oooutlk  I'am absolutely newbee in rust.  Implement `String2Tree<String>` [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d08b358f366d75bea3dc0ebc194092bb)

Could you review my code ?

**Comment by oooutlk** [comment]
Thanks for helping to improve this library. Currently I do not think it is feasible to construct a `Tree` from `String`.

Current string representation of trees utilize parentheses to group child nodes and spaces to separate them. Thus '(', ')' and ' ' should be escaped as e.g. "\\(", "\\)" or "\\ " in tree data field.

And, if we take it seriously, we should pick up some well known data format for the serialization of trees, e.g. XML, JSON or something, and the deserialization work could be done via serde.

This feature may be introduced in future version. But I do not have clear idea yet.
